# Use Python base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code (producer or consumer)
COPY kafka_producer.py .

# Default command (can be overridden by docker-compose)
CMD ["python", "kafka_producer.py"]
